### ISSUE TITLE
wptide.org domain has lapsed ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by tomjn** [wptide/wptide.org#111]
The domain name didn't get renewed

<img width="713" alt="Screenshot 2022-10-12 at 12 07 52" src="https://user-images.githubusercontent.com/58855/195327280-ea80f29b-55bb-4fe7-81b0-471cc013fac9.png">

**Comment by tomjn** [comment]
this is the `www.` subdomain that's linked from the Make .org blog

**Comment by jeffpaul** [comment]
@derekherman I can remove the subdomain on the Make reference, but curious if something changed on the domain record for the www entry?

**Comment by derekherman** [comment]
The www should redirect is it not currently doing that?

**Comment by tomjn** [comment]
@derekherman nope, it doesn't find a DNS record for the `www` subdomain so there's nothing to perform the redirection

**Comment by derekherman** [comment]
The DNS has been updated. However, Firebase needs to provision the certificate still and DNS needs to finish propagating. This issue will automatically be addressed within 24 hours. I'll circle back and close once it's been fixed.

**Comment by jeffpaul** [comment]
www.wptide.org appears to be resolving now, so closing this.  Thanks @tomjn for flagging this!

**Comment by tomjn** [comment]
URL working for me too, thanks!
