### ISSUE TITLE
PHP Compatibility Checker Slider Revolution 6.2.22 bug

### ISSUE THREAD

**Issue by momoteb** [wptide/wptide.org#123]
## Bug Description

PHP Compatibility Checker
Scan blocked on Slider Revolution 6.2.22 

I got this 

Response status: 404

Message: The audit requested does not exist

## Additional context

- Tide version:
- Node version:
- Docker version (if applicable):
- OS:
- Browser: [e.g. chrome, safari]
- Device: [e.g. iPhone8]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

*

**Comment by jeffpaul** [comment]
@momoteb https://wordpress.org/plugins/search/Slider+Revolution/ does not appear to be a valid plugin on the wp.org repo. I'm closing this as Tide only audits plugins available publicly on the wp.org repo.
