### ISSUE TITLE
Plugin stuck at Elementor

### ISSUE THREAD

**Issue by tovabbi** [wptide/wptide.org#127]
## Regression Description

The WP plugin scan stops at the Elementor Pro plugin with the following message:

Elementor Pro 3.13.2
Response status: 404
Message: The audit requested does not exist.

## Additional context

- Tide version:
- Node version:
- Docker version (if applicable):
- OS:
- Browser: [e.g. chrome, safari]
- Device: [e.g. iPhone8]

WP 6.2.2, PHP Compatibility Checker 1.6.2, self-hosted nginx

According to the FAQ, I should report this here: https://wordpress.org/plugins/php-compatibility-checker/#faq
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

*

**Comment by jeffpaul** [comment]
@tovabbi https://wordpress.org/plugins/search/Elementor+Pro/ does not appear to be a valid plugin on the wp.org repo.  I'm closing this as Tide only audits plugins available publicly on the wp.org repo.
