### ISSUE TITLE
Scan stucks with first plugin

### ISSUE THREAD

**Issue by laxtnog** [wptide/wptide.org#129]
## Bug Description
PHP compatibility  checker stucks checkig first plugin

## Expected Behaviour

scan all the plugins

## Steps to reproduce

Click on Scan and just stucks 

## Screenshots

![image](https://github.com/wptide/wptide.org/assets/108299626/88852e96-c8a2-4205-abd7-21f2f7654e69)

**Comment by jeffpaul** [comment]
@laxtnog https://wordpress.org/plugins/search/advanced+custom+fields+pro/ does not appear to be a valid plugin on the wp.org repo. I'm closing this as Tide only audits plugins available publicly on the wp.org repo.
