### ISSUE TITLE
PHP Compatibility Checker sticking

### ISSUE THREAD

**Issue by IanSHart** [wptide/wptide.org#131]
## Regression Description

Version 1.6.2 of PHP Compatability Checker is stuck at one plugiin.
message:

DreamHost Panel Login 1.0.0
Response status: failed
Message: The audit of this code was interrupted, please scan again.
any attempt to rescan results in the same message.

## Expected Behaviour

Expected the plugin to report on campatability of all plugins and theme.
## Screenshots

![start scan](https://github.com/wptide/wptide.org/assets/138898159/f7f057e5-2d26-4b49-9939-beb1551019ac)
![scan stuck](https://github.com/wptide/wptide.org/assets/138898159/c64a53b6-e20d-49fb-810e-e6383f553c31)

## Additional context

- Tide version:
- Node version:
- Docker version (if applicable):
- OS: Windows 10
- Browser: [e.g. chrome, safari] Firefox
- Device: [e.g. iPhone8] Dell PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

*

**Comment by IanSHart** [comment]
This plugin relies on Tide that constantly scans updated versions of plugins and themes in the background.

**Comment by jeffpaul** [comment]
@IanSHart https://wordpress.org/plugins/search/DreamHost%2520Panel%2520Login/ does not appear to be a valid plugin on the wp.org repo. I'm closing this as Tide only audits plugins available publicly on the wp.org repo.
