### ISSUE TITLE
PHP Compatibility Checker - Stuck on plugin "Dreamhost Panel Login 1.0.0"

### ISSUE THREAD

**Issue by cillalater** [wptide/wptide.org#133]
## Bug Description

Compatibility scan stops on the plugin "Dreamhost Panel Login 1.0.0" and will not continue to the remaining plugins.

The Dreamhost plugin is the 3rd in the list, so the scan doesn't get very far.

I've tried this on a couple websites I manage, both hosted in Dreamhost, and the scan fails at the same plugin.

I'm not sure why this is, but the Dreamhost plugin is not listed in my Wordpress list of plugins. So I can't disable it and skip it during the scan.

Error displayed in the plugin section is as follows:

<i>DreamHost Panel Login 1.0.0

Response status: failed

Message: The audit of this code was interrupted, please scan again.</i>

## Expected Behaviour

I do not get the PHP compatibility list that it gives with the other plugins and the scan does not continue despite the "Now scanning" status.

## Steps to reproduce
I just run the scan. Tried with all plugins and including inactive plugins. Same result.

## Additional context

Hosted by DreamHost. Running on Wordpress 6.2.2

 I've inquired with Dreamhost about this plugin since I never installed it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

*

**Comment by jeffpaul** [comment]
@cillalater https://wordpress.org/plugins/search/Dreamhost+Panel+Login/ does not appear to be a valid plugin on the wp.org repo. I'm closing this as Tide only audits plugins available publicly on the wp.org repo.
